trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Setup
    jobs:
      - job: Install
        steps:
          - script: echo "Setting up environment"
            displayName: 'Setup Environment'
          # Add your setup commands here
          # - script: npm install
          #   displayName: 'Install Dependencies'

  - stage: Test
    dependsOn: Setup
    jobs:
      - job: RunTests
        steps:
          - script: echo "Running tests"
            displayName: 'Run Tests'
          # Add your test commands here
          # - script: npm test
          #   displayName: 'Execute Tests'

  - stage: Build
    dependsOn: Test
    jobs:
      - job: BuildApp
        steps:
          - script: echo "Building project"
            displayName: 'Build Project'
          # Add your build commands here
          # - script: npm run build
          #   displayName: 'Build Application'
          # - task: CopyFiles@2
          #   inputs:
          #     contents: 'dist/**'
          #     targetFolder: '$(Build.ArtifactStagingDirectory)'
          # - task: PublishBuildArtifacts@1
          #   inputs:
          #     pathToPublish: '$(Build.ArtifactStagingDirectory)'
          #     artifactName: 'drop'

  - stage: Deploy
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: DeployApp
        steps:
          - script: echo "Deploying application"
            displayName: 'Deploy Application'
          # Add your deployment commands here
          # - task: DownloadBuildArtifacts@0
          #   inputs:
          #     buildType: 'current'
          #     downloadType: 'single'
          #     artifactName: 'drop'
          #     downloadPath: '$(System.ArtifactsDirectory)'
          # - script: npm run deploy
          #   displayName: 'Deploy to Production' 