version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            echo "Setting up environment"
            # Add your setup commands here
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: |
            echo "Running tests"
            # Add your test commands here

  build:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Application
          command: |
            echo "Building project"
            # Add your build commands here
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy Application
          command: |
            echo "Deploying application"
            # Add your deployment commands here

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main 