name: Build and Deploy with Netlify

on:
  push:
    branches: [ main, dev, develop, development, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set branch name and build parameters
        id: branch
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "is_production=true" >> $GITHUB_OUTPUT
            echo "alias=production" >> $GITHUB_OUTPUT
          else
            echo "is_production=false" >> $GITHUB_OUTPUT
            echo "alias=$BRANCH_NAME" >> $GITHUB_OUTPUT
          fi
      
      # Add setup steps specific to your project here
      # For example, for a Node.js project:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build site
        run: |
          if [[ "${{ steps.branch.outputs.is_production }}" == "true" ]]; then
            npm run build
          else
            npm run build:preview
          fi
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: ${{ steps.branch.outputs.alias }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 5 