name: Build and Deploy with Vercel

on:
  push:
    branches: [ main, dev, develop, development, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set branch name and build parameters
        id: branch
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "is_production=true" >> $GITHUB_OUTPUT
          else
            echo "is_production=false" >> $GITHUB_OUTPUT
            # Replace slashes with hyphens for valid branch names
            SAFE_BRANCH=$(echo "$BRANCH_NAME" | sed 's/\//-/g')
            echo "branch_alias=$SAFE_BRANCH" >> $GITHUB_OUTPUT
          fi
      
      # Add setup steps specific to your project here
      # For example, for a Node.js project:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build site
        run: |
          if [[ "${{ steps.branch.outputs.is_production }}" == "true" ]]; then
            npm run build
          else
            npm run build
          fi
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: ${{ steps.branch.outputs.is_production == 'true' && '--prod' || '' }}
          working-directory: ./ 